name: dotnet package

on: 
  pull_request:
    branches:
      - main
      - dev
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK 5.0.x
        uses: actions/setup-dotnet@v1.7.2
        with:
          fetch-depth: 0
          dotnet-version: 5.0.x
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
        # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        args: >
        -Dsonar.organization= ${{ secrets.ORGANISATION }}
        -Dsonar.projectKey= ${{ secrets.SONAR_TOKEN }}
      - name: Publish
        run: dotnet publish --configuration Release --no-restore
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: AdeptApi
          path: /home/runner/work/ADEPT-API/ADEPT-API/ADEPT-API/bin/Release/net5.0/publish/


